spring:
  application:
    name: mall-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.196.111.123:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: Wenjia123
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: b0d0249b-c35a-4257-8ad2-4fe450e88e2e
#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: 127.0.0.1:8080

#    redis:
#      host: 127.0.0.1
#      port: 6379

server:
  port: 10000
#  servlet:
#    session:
#      timeout: 30m
#开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

    #关闭thymeleaf缓存
#  thymeleaf:
#    cache: false
#
#  session:
#    store-type: redis


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: showStatus  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.mall.mallproduct: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'